# Background

Sebagai data scientist, tugas utama kita akan selalu bergelut dengan data. Namun, selama ini, apakah kita sadar darimana data kita berasal? bagaimana data kita dikumpulkan? dsb dsb? Untuk menjadi seorang data scientist yang baik, saya rasa pengetahuan dan pengalmaan dalam mengumpulkan data cukup penting. Apakah anda pernah kesulitan dalam mencari data? apakah anda pernah kesulitan dalam melakukan pelabelan data? apakah kalian percaya bahwa data seharusnya gratis dan mudah untuk diakses. It's Data for Democracy!

Untuk membuat data dapat diakses oleh semua orang, pihak penyedia jasa juga harus memberikan batasan guna mengurangi penggunaan berlebihan dan penyalahgunaan data oleh pihak-pihak yang tidak bertanggungjawab. Untuk menanggulangi permasalahn ini, kita bisa memanfaatkan teknologi API (Application Program Interface). Dengan API, kita dapat mengatur bagaimana data kita dapat diakses secara umum.

Dalam Capstone kali ini, kita akan mencoba membuat API menggunakan python + flask agar data kita dapat diakses secara umum. Secara konsep, kita akan membangun aplikasi python menggunakan flask yang dapat mengatur, membaa, dan mengirimkan response terhadap request user.

**Data yang digunakan:** 
- chinook.db

**Environtments:**
- python 
- pandas
- flask 
- gunicorn


**Goals**
1. Berhasil membuat Flask APP yang berfungsi sebagai API yang memberikan data dalam format JSON
2. Berhasil membuat minimal 2 endpoint statis (atau lebih) dan 1 endpoint dinamis(atau lebih) menggunakan routing
3. Berhasil melakukan deployment Flask APP ke Heroku

*Notes: menggunakan endpoints yang sudah dicontohkan tidak akan dihitung sebagai endpoint hasil kerja capstone*

# Membangun API Python dalam 6 menit 
*Disclaimer: Course ini adalah course singkat untuk memperkenalkan student kedalam dunia **backend**. Akan ada sangat banyak kekurangan dari konsep API yang ada saat ini. Untuk kemudahan, kita hanya akan membahas konsep dasar dari API dan dan mewujudkannya dalam bentuk Flask App

Kita akan mencoba membangun Flask App sebagai API, oleh karena itu jika belum memiliki library `Flask`, silakan install menggunakan `pip install flask`. Berikut adalah beberapa library yang akan kita butuhkan. Cobalah import library tersebut sebelum menginstallnya.

In [1]:
# !pip install flask
# !pip install pandas
# !pip install requests
# !pip install gunicorn

In [1]:
import flask

In [2]:
import pandas as pd

In [3]:
import requests

In [4]:
import gunicorn

In [5]:
#mendapatkan buku
books = pd.read_csv('data/books_c.csv')
books

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.56,0439785960,9780439785969,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.49,0439358078,9780439358071,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,0439554934,9780439554930,eng,320,5629932,70390
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439554896,9780439554893,eng,352,6267,272
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.55,043965548X,9780439655484,eng,435,2149872,33964
...,...,...,...,...,...,...,...,...,...,...
13709,47699,M Is for Magic,Neil Gaiman-Teddy Kristiansen,3.82,0061186422,9780061186424,eng,260,11317,1060
13710,47700,Black Orchid,Neil Gaiman-Dave McKean,3.72,0930289552,9780930289553,eng,160,8710,361
13711,47701,InterWorld (InterWorld #1),Neil Gaiman-Michael Reaves,3.53,0061238961,9780061238963,en-US,239,14334,1485
13712,47708,The Faeries' Oracle,Brian Froud-Jessica Macbeth,4.43,0743201116,9780743201117,eng,224,1550,38
13713,47709,The World of The Dark Crystal,Brian Froud,4.29,1862056242,9781862056244,eng,132,3572,33

In [8]:
#mendapatkan nama pengarang
books = pd.read_csv('data/books_c.csv')
condition = books['authors'] == 'J.K. Rowling'  
books = books[condition]
books

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.56,0439785960,9780439785969,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.49,0439358078,9780439358071,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,0439554934,9780439554930,eng,320,5629932,70390
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439554896,9780439554893,eng,352,6267,272
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.55,043965548X,9780439655484,eng,435,2149872,33964
5,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling,4.78,0439682584,9780439682589,eng,2690,38872,154
7,10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,0439827604,9780439827607,eng,3342,27410,820
693,2002,Harry Potter Schoolbooks Box Set: Two Classic ...,J.K. Rowling,4.40,043932162X,9780439321624,eng,240,11459,143
695,2005,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.56,0747584664,9780747584667,eng,768,1173,72
1123,3357,Harry Potter Y La Piedra Filosofal (Harry Pott...,J.K. Rowling,4.47,0613359607,9780613359603,spa,254,84,5
1429,4256,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.55,074757362X,9780747573623,eng,480,3116,147
5295,15875,Harry Potter y la cámara secreta (Harry Potter...,J.K. Rowling,4.41,8498380138,9788498380132,spa,288,181,15
5296,15876,Harry Potter y la Orden del Fénix (Harry Potte...,J.K. Rowling,4.49,8478888845,9788478888849,spa,893,4893,397
5300,15881,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439064864,9780439064866,eng,341,2115562,32694
10519,34258,Harry Potter y la Orden del Fénix (Harry Potte...,J.K. Rowling,4.49,8478887423,9788478887422,spa,896,953,51
10540,34318,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,0786222727,9780786222728,eng,424,132,12
12253,41907,Harry Potter und die Kammer des Schreckens (Ha...,J.K. Rowling,4.41,3551552096,9783551552099,ger,351,25,1
12256,41911,Harry Potter und der Gefangene von Askaban (Ha...,J.K. Rowling,4.55,355155210X,9783551552105,ger,448,28,2
12257,41912,Harry Potter ve Felsefe Taşı,J.K. Rowling,4.47,3570211010,9783570211014,tur,353,12,0
12660,43504,Harry Potter and the Philosopher's Stone (Harr...,J.K. Rowling,4.47,158234681X,9781582346816,gla,250,11,0
12663,43509,Harry Potter and the Goblet of Fire (Harry Pot...,J.K. Rowling,4.55,074754624X,9780747546245,eng,636,18097,860
13634,47523,Harry Potter Boxed Set (Harry Potter #1-4),J.K. Rowling,4.67,0439434866,9780439434867,eng,1820,534,6
13637,47532,Harry Potter y el prisionero de Azkaban (Harry...,J.K. Rowling,4.55,8478886559,9788478886555,spa,359,5582,469

In [9]:
#mendapatkan judul buku
books = pd.read_csv('data/books_c.csv')
condition = books['title'] == 'Black Orchid'  
books = books[condition]
books

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
13710,47700,Black Orchid,Neil Gaiman-Dave McKean,3.72,0930289552,9780930289553,eng,160,8710,361

In [10]:
# menghitung statistik buku
books = pd.read_csv('data/books_c.csv')
results = books.describe()
results

,bookID,average_rating,isbn13,# num_pages,ratings_count,text_reviews_count
count,13714.000000,13714.000000,1.371400e+04,13714.000000,1.371400e+04,13714.000000
mean,22159.859195,3.930620,9.764017e+12,342.402727,1.776540e+04,533.632128
std,13700.926816,0.357893,3.987679e+11,252.650165,1.129572e+05,2529.006691
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000e+00,0.000000
25%,10619.250000,3.770000,9.780345e+12,196.000000,8.300000e+01,7.000000
50%,21321.500000,3.960000,9.780613e+12,301.000000,6.305000e+02,40.000000
75%,33311.750000,4.130000,9.780940e+12,421.000000,4.742250e+03,222.000000
max,47709.000000,5.000000,9.790008e+12,6576.000000,5.629932e+06,93619.000000

In [18]:
books = pd.read_csv('data/books_c.csv')
books.sort_values(by='average_rating', ascending=False)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
6077,18184,The Complete Theory Fun Factory: Music Theory ...,Ian Martin-Katie Elliott,5.0,0851621813,9780851621814,eng,96,1,0
4939,14741,Zone of the Enders: The 2nd Runner Official St...,Tim Bogenn,5.0,0744002354,9780744002355,eng,128,2,0
963,2843,Literature Circle Guide: Bridge to Terabithia:...,Tara MacCarthy,5.0,0439271711,9780439271714,eng,32,4,1
7506,23552,The New Big Book of America,Todd Davis-Marc Frey,5.0,0762412631,9780762412631,eng,56,2,1
11067,36781,Bubbles in the Middle (The Powerpuff Girls Plu...,Aaron Rosenberg-Christopher Cook,5.0,0439332613,9780439332613,eng,64,5,0
...,...,...,...,...,...,...,...,...,...,...
12014,41044,Day and Night,Better Homes and Gardens,0.0,0696018829,9780696018824,eng,32,0,1
9129,29404,Your Child and Jesus: A Family Activity Book,Rick Osborne-Kevin Miller,0.0,080242855X,9780802428554,eng,112,0,0
4181,12712,Brodie's notes on Aldous Huxley's brave new world,Graham Handley,0.0,0333581296,9780333581292,eng,71,0,0
6425,19257,Canopy: A Work for Voice and Light in Harvard ...,David Ward-Parveen Adams-Seamus Heaney-Ivan ...,0.0,0916724948,9780916724948,eng,63,0,0
8239,25841,The Road To War 1933 39,Andrew Hunt,0.0,0340774770,9780340774779,eng,128,0,0

In [13]:
# menghitung statistik buku
books = pd.read_csv('data/books_c.csv')
results = books.describe()
results

,bookID,average_rating,isbn13,# num_pages,ratings_count,text_reviews_count
count,13714.000000,13714.000000,1.371400e+04,13714.000000,1.371400e+04,13714.000000
mean,22159.859195,3.930620,9.764017e+12,342.402727,1.776540e+04,533.632128
std,13700.926816,0.357893,3.987679e+11,252.650165,1.129572e+05,2529.006691
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000e+00,0.000000
25%,10619.250000,3.770000,9.780345e+12,196.000000,8.300000e+01,7.000000
50%,21321.500000,3.960000,9.780613e+12,301.000000,6.305000e+02,40.000000
75%,33311.750000,4.130000,9.780940e+12,421.000000,4.742250e+03,222.000000
max,47709.000000,5.000000,9.790008e+12,6576.000000,5.629932e+06,93619.000000

In [44]:
#Buku dengan rating rata-rata di atas 3
books = pd.read_csv('data/books_c.csv')
condition = books['average_rating'] >= 3
books = books[condition]
books

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.56,0439785960,9780439785969,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.49,0439358078,9780439358071,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,0439554934,9780439554930,eng,320,5629932,70390
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439554896,9780439554893,eng,352,6267,272
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.55,043965548X,9780439655484,eng,435,2149872,33964
...,...,...,...,...,...,...,...,...,...,...
13709,47699,M Is for Magic,Neil Gaiman-Teddy Kristiansen,3.82,0061186422,9780061186424,eng,260,11317,1060
13710,47700,Black Orchid,Neil Gaiman-Dave McKean,3.72,0930289552,9780930289553,eng,160,8710,361
13711,47701,InterWorld (InterWorld #1),Neil Gaiman-Michael Reaves,3.53,0061238961,9780061238963,en-US,239,14334,1485
13712,47708,The Faeries' Oracle,Brian Froud-Jessica Macbeth,4.43,0743201116,9780743201117,eng,224,1550,38
13713,47709,The World of The Dark Crystal,Brian Froud,4.29,1862056242,9781862056244,eng,132,3572,33

In [46]:
#Buku dengan rating rata-rata di bawah 3
books = pd.read_csv('data/books_c.csv')
condition = books['average_rating'] <= 3
books = books[condition]
books

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
101,159,Dinner with Anna Karenina,Gloria Goldreich,2.96,0778322270,9780778322276,eng,368,400,64
291,799,Out to Eat London 2002 (Lonely Planet Out to Eat),Lonely Planet-Mark Honan,0.00,1740592050,9781740592055,eng,295,0,0
424,1302,Juiced Official Strategy Guide,Doug Walsh,0.00,0744005612,9780744005615,eng,112,0,0
565,1584,Cliffs Notes on Aristophanes' Lysistrata The ...,W. John Campbell,2.33,0822007762,49086007763,eng,80,3,0
587,1658,American Government: Continuity and Change Al...,Karen O'Connor-Larry J. Sabato,2.95,0321317106,9780321317100,eng,664,0,0
...,...,...,...,...,...,...,...,...,...,...
13400,46387,Advances in Polymer Science Volume 194: Enzym...,Shiro Kobayashi-David L. Kaplan-Helmut Ritter,0.00,3540292128,9783540292128,eng,254,0,0
13490,46775,100 Strokes of the Brush Before Bed,Melissa Panarello-Lawrence Venuti,2.57,0802117813,9780802117816,eng,176,2655,199
13595,47295,Il genio e l'alienista: La strana visita di Lo...,Paolo Mazzarello,0.00,8870883019,9788870883015,ita,94,0,0
13627,47461,My Dirty Thirties: Male/Female/Male,Kelly Carr,2.44,1932420304,9781932420302,eng,152,6,2
13645,47551,La habitacion oscura,Sofía Irene Cardona,0.00,0977601331,9780977601332,spa,64,0,0

In [39]:
books = pd.read_csv('data/books_c.csv')
books.sort_values(by='ratings_count',ascending=False)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,0439554934,9780439554930,eng,320,5629932,70390
12243,41865,Twilight (Twilight #1),Stephenie Meyer,3.59,0316015849,9780316015844,eng,498,4367341,93619
2000,5907,The Hobbit or There and Back Again,J.R.R. Tolkien,4.26,0618260307,9780618260300,eng,366,2364968,31664
1717,5107,The Catcher in the Rye,J.D. Salinger,3.80,0316769177,9780316769174,eng,277,2318478,42016
340,960,Angels & Demons (Robert Langdon #1),Dan Brown,3.88,1416524797,9781416524793,eng,736,2279854,20851
...,...,...,...,...,...,...,...,...,...,...
10542,34320,Operation Spy School (Adam Sharp #4),George E. Stanley-Guy Francis,3.65,0375824049,9780375824043,eng,44,0,0
12955,44705,The Leadership Challenge: Skills for Taking Ch...,Warren G. Bennis,0.00,088684049X,9780886840495,eng,60,0,0
1122,3351,Open City 6: The Only Woman He Ever Left,Open City Magazine-James Purdy-Daniel Pinchbec...,0.00,189044717X,9781890447175,eng,200,0,0
3744,11516,Les Larmes d'Icare,Dan Simmons-Jean-Daniel Brèque,3.56,220724038X,9782207240380,fre,357,0,0
12014,41044,Day and Night,Better Homes and Gardens,0.00,0696018829,9780696018824,eng,32,0,1

In [11]:
# buku yang dirating di atas 1000.000 rating
books = pd.read_csv('data/books_c.csv')
condition  = books['ratings_count'] >= 1000000
books = books[condition]
books

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.56,0439785960,9780439785969,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.49,0439358078,9780439358071,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,0439554934,9780439554930,eng,320,5629932,70390
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.55,043965548X,9780439655484,eng,435,2149872,33964
25,34,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. Tolkien,4.35,0618346252,9780618346257,eng,398,2009749,12784
313,865,The Alchemist,Paulo Coelho-Alan R. Clarke-Özdemir İnce,3.85,0061122416,9780061122415,eng,197,1592632,54668
324,890,Of Mice and Men,John Steinbeck,3.86,0142000671,9780142000670,eng,112,1654353,23959
330,930,Memoirs of a Geisha,Arthur Golden,4.10,0739326228,9780739326220,eng,434,1301305,19452
340,960,Angels & Demons (Robert Langdon #1),Dan Brown,3.88,1416524797,9781416524793,eng,736,2279854,20851
343,968,The Da Vinci Code (Robert Langdon #2),Dan Brown,3.82,0307277674,9780307277671,eng,489,1588890,35316
664,1934,Little Women,Louisa May Alcott,4.06,0451529308,9780451529305,eng,449,1402458,15525
1014,2956,The Adventures of Huckleberry Finn,Mark Twain-Guy Cardwell-John Seelye,3.81,0142437174,9780142437179,eng,327,1022438,11005
1211,3636,The Giver,Lois Lowry,4.12,0385732554,9780385732550,eng,208,1464909,54469
1717,5107,The Catcher in the Rye,J.D. Salinger,3.80,0316769177,9780316769174,eng,277,2318478,42016
1724,5129,Brave New World,Aldous Huxley-Felisberto Albuquerque,3.98,0060929871,9780060929879,eng,288,1173739,18665
2000,5907,The Hobbit or There and Back Again,J.R.R. Tolkien,4.26,0618260307,9780618260300,eng,366,2364968,31664
2077,6185,Wuthering Heights,Emily Brontë-Richard J. Dunn-David Timson-Char...,3.84,0393978893,9780393978896,eng,464,1041597,20192
2505,7613,Animal Farm,George Orwell,3.91,0452284244,9780452284241,eng,122,2102616,29469
2508,7624,Lord of the Flies,William Golding,3.67,0140283331,9780140283334,eng,182,1861140,24622
3293,10210,Jane Eyre,Charlotte Brontë-Michael Mason-João Gaspar Ro...,4.11,0142437204,9780142437209,eng,532,1328143,26386
4455,13496,A Game of Thrones (A Song of Ice and Fire #1),George R.R. Martin,4.45,0553588486,9780553588484,eng,848,1598396,37379
5300,15881,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439064864,9780439064866,eng,341,2115562,32694
5320,15931,The Notebook (The Notebook #1),Nicholas Sparks,4.08,0553816713,9780553816716,eng,214,1090301,15327
6066,18135,Romeo and Juliet,William Shakespeare-Paul Werstine-Barbara A. M...,3.74,0743477111,9780743477116,eng,283,1811259,14102
6363,19063,The Book Thief,Markus Zusak,4.37,0375831002,9780375831003,eng,552,1410666,84237
6522,19501,Eat Pray Love,Elizabeth Gilbert,3.54,0143038419,9780143038412,eng,368,1309623,47291
7723,24178,Charlotte's Web,E.B. White-Garth Williams-Rosemary Wells,4.16,0064410935,9780064410939,eng,184,1229902,13915
8749,28187,The Lightning Thief (Percy Jackson and the Oly...,Rick Riordan,4.24,0786838655,9780786838653,eng,377,1645445,45829
9319,30119,Where the Sidewalk Ends,Shel Silverstein,4.30,0060513039,9780060513030,eng,176,1094416,9754
11201,37435,The Secret Life of Bees,Sue Monk Kidd,4.04,0142001740,9780142001745,eng,302,1007862,25677
12243,41865,Twilight (Twilight #1),Stephenie Meyer,3.59,0316015849,9780316015844,eng,498,4367341,93619
12689,43641,Water for Elephants,Sara Gruen,4.08,1565125606,9781565125605,eng,335,1198632,52449

In [51]:
#  menunjukkan buku berbahasa Inggris
books = pd.read_csv('data/books_c.csv')
condition  = books['language_code'] == 'eng'
books = books[condition]
books

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.56,0439785960,9780439785969,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.49,0439358078,9780439358071,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,0439554934,9780439554930,eng,320,5629932,70390
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439554896,9780439554893,eng,352,6267,272
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.55,043965548X,9780439655484,eng,435,2149872,33964
...,...,...,...,...,...,...,...,...,...,...
13708,47697,The Sandman: King of Dreams,Alisa Kwitney-Neil Gaiman,4.62,0811835928,9780811835923,eng,180,12775,34
13709,47699,M Is for Magic,Neil Gaiman-Teddy Kristiansen,3.82,0061186422,9780061186424,eng,260,11317,1060
13710,47700,Black Orchid,Neil Gaiman-Dave McKean,3.72,0930289552,9780930289553,eng,160,8710,361
13712,47708,The Faeries' Oracle,Brian Froud-Jessica Macbeth,4.43,0743201116,9780743201117,eng,224,1550,38
13713,47709,The World of The Dark Crystal,Brian Froud,4.29,1862056242,9781862056244,eng,132,3572,33

In [12]:
#menampilkan daftar buku dengan metode stack - unstack
books = pd.read_csv('data/books_c.csv')
results = books.stack().unstack()
results

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.56,0439785960,9780439785969,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.49,0439358078,9780439358071,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,0439554934,9780439554930,eng,320,5629932,70390
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439554896,9780439554893,eng,352,6267,272
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.55,043965548X,9780439655484,eng,435,2149872,33964
...,...,...,...,...,...,...,...,...,...,...
13709,47699,M Is for Magic,Neil Gaiman-Teddy Kristiansen,3.82,0061186422,9780061186424,eng,260,11317,1060
13710,47700,Black Orchid,Neil Gaiman-Dave McKean,3.72,0930289552,9780930289553,eng,160,8710,361
13711,47701,InterWorld (InterWorld #1),Neil Gaiman-Michael Reaves,3.53,0061238961,9780061238963,en-US,239,14334,1485
13712,47708,The Faeries' Oracle,Brian Froud-Jessica Macbeth,4.43,0743201116,9780743201117,eng,224,1550,38
13713,47709,The World of The Dark Crystal,Brian Froud,4.29,1862056242,9781862056244,eng,132,3572,33

In [67]:
# endpoint yang menunjukkan crosstab buku berdasarkan bahasa dengan metode group by
books = pd.read_csv('data/books_c.csv')
results = books.groupby('language_code').mean().sort_values(by='average_rating',ascending=False)
results

,bookID,average_rating,isbn13,# num_pages,ratings_count,text_reviews_count
language_code,,,,,,
wel,25426.000000,5.000000,9.780862e+12,150.000000,1.000000,0.000000
gla,43504.000000,4.470000,9.781582e+12,250.000000,11.000000,0.000000
zho,21911.750000,4.368750,9.789717e+12,320.875000,20.437500,0.750000
ale,44012.000000,4.360000,9.780345e+12,512.000000,99.000000,15.000000
lat,13186.000000,4.346667,9.781349e+12,200.333333,109.666667,13.333333
dan,2977.000000,4.280000,9.788777e+12,258.000000,11.000000,0.000000
jpn,22065.625000,4.264531,9.784232e+12,192.406250,62.468750,2.859375
tur,35313.333333,4.240000,9.785630e+12,433.333333,284.333333,12.333333
heb,27575.000000,4.220000,9.789651e+12,593.000000,95.000000,7.000000
rus,26405.714286,4.201429,9.784735e+12,497.571429,1415.571429,31.000000
mul,16759.714286,4.121905,9.781242e+12,438.238095,2033.952381,73.571429
msa,22277.000000,4.100000,9.789833e+12,784.000000,27.000000,6.000000
en-CA,18609.666667,4.057778,9.780873e+12,332.111111,3569.111111,291.555556
fre,22304.440191,3.984354,9.782317e+12,342.071770,2704.885167,53.674641
por,33907.370370,3.944444,9.788931e+12,336.370370,182.000000,11.333333
spa,25958.019093,3.935060,9.787122e+12,377.443914,4196.921241,92.608592
eng,21756.851614,3.929522,9.763886e+12,340.156032,21989.320464,651.476874
en-GB,24223.178886,3.923666,9.754303e+12,334.912023,2404.595308,96.665689
en-US,23006.025309,3.920477,9.753440e+12,345.408476,4282.848146,189.970571
ger,23566.210084,3.908109,9.783388e+12,383.487395,463.831933,17.756303
enm,12742.666667,3.873333,9.780310e+12,1060.333333,3157.000000,82.333333
grc,9866.416667,3.803333,9.780815e+12,413.083333,48.250000,2.166667
ita,24588.157895,3.737368,9.787557e+12,368.789474,1371.789474,35.210526
nl,30785.571429,3.700000,9.789036e+12,426.714286,471.428571,12.142857
swe,28501.166667,3.671667,9.787859e+12,373.000000,2153.500000,68.833333
ara,2648.000000,3.625000,9.789864e+12,410.000000,84.000000,8.500000
nor,32592.000000,3.590000,9.780970e+12,185.000000,86.000000,8.000000
glg,23106.000000,3.507500,9.788471e+12,312.750000,172.000000,8.500000
cat,23143.666667,3.190000,9.788476e+12,210.333333,120.666667,8.000000
srp,10200.000000,0.000000,9.788644e+12,222.000000,0.000000,0.000000

In [66]:
# endpoint yang menunjukkan crosstab buku berdasarkan penulis dengan metode group by
books = pd.read_csv('data/books_c.csv')
results = books.groupby('authors').mean().sort_values(by='average_rating',ascending=False)
results

,bookID,average_rating,isbn13,# num_pages,ratings_count,text_reviews_count
authors,,,,,,
Ross Garnaut,23276.0,5.0,9.780198e+12,350.0,1.0,0.0
John Diamond,17224.0,5.0,9.781891e+12,74.0,5.0,3.0
Laura Driscoll-Alisa Klayman-Grodsky-Eric Weiner,36853.0,5.0,9.780787e+12,24.0,2.0,1.0
Svetlana Alpers,4874.0,5.0,9.780199e+12,532.0,1.0,0.0
Aristophanes-F.W. Hall-W.M. Geldart,2034.0,5.0,9.780198e+12,364.0,0.0,0.0
...,...,...,...,...,...,...
Lonely Planet-Mark Honan,799.0,0.0,9.781741e+12,295.0,0.0,0.0
John Weld-Phil Interlandi,24010.0,0.0,9.781565e+12,285.0,0.0,0.0
Apollodorus-Richard Wagner,27416.0,0.0,9.783599e+12,335.0,0.0,0.0
Shiro Kobayashi-David L. Kaplan-Helmut Ritter,46387.0,0.0,9.783540e+12,254.0,0.0,0.0
Graham Handley,12712.0,0.0,9.780334e+12,71.0,0.0,0.0

Membuat aplikasi Flask sesederhana menulis code dalam 7 baris !
cobalah buat file `app.py` yang berisi script berikut :

```python
from flask import Flask, request 
app = Flask(__name__) 

@app.route('/home')
def home():
    return 'Hello World'

if __name__ == '__main__':
    app.run(debug=True, port=5000)
```

Setelah membuat file `app.py` berisikan script diatas, cobalah jalankan file tersebut melalui terminal dengan masuk ke direktori yang sama dengan file tersebut, dan jalankan sintaks `python app.py`. Setelah menjalankan sintaks tersebut, maka aplikasi kita akan berjalan dengan alamat `localhost` dengan port `5000`, atau dapat kalian akses melalui browser dengan alamat `localhost:5000`. 

pada baris ke-4, terdapat sintaks `@app.route('/home')`, yang berarti bahwa fungsi atau method dibawahnya (fungsi `home`) akan dijalankan ketika user mengakses rute atau alaman `/home`. Sekarang, cobalah akses `localhost:5000/home`, maka kalian akan mendapatkan tulisan 'Hello World'

Pada baris terakhir, `debug=True` akan menampilkan semua log aktivitas dari app kita dalam terminal/comman prompt/shell dimana app kita dijalankan. 

Dari contoh script diatas, kita dapat katakan bahwa rute atau `route` adalah endpoints, atau tempat dimana sistem dan user saling bersentuhan. Dalam kasus diatas, untuk mendapatkan 'Hello World', maka kita harus mengakses endpoint `/home`. Sekali lagi, **representasi endpoint adalah route**.

## Query Arguments

Setelah mengetahui kerangka utama dalam membuat aplikasi Flask, cukup penting untuk mengetahui Query Arguments. Ketika kita melakukan pencarian pada mesin pencari seperti google.com, jika kita perhatikan pada alamat (url) yang diberikan, terdapat query arguments yang diberikan setelah `google.com/` yang diawali dengan `?`. 

Format query pada url pada ummnya adalah `example.com?arg1=value1&arg2=value2`, dimana query akan diawali dengan `?`, dihubungkan dengan `&`, dan setiap query adalah pasangan `key` dan `value`

```python
from flask import Flask, request 
app = Flask(__name__) 

@app.route('/query')
def query_example():
    key1 = 'name'
    key2 = 'age'
    name = request.args[key1] # Jika key tidak disertakan dalam URL, maka akan terjadi server error
    age = request.args.get(key2) # Jika key tidak disertakan dalam URL, maka age akan bernilai None
    return(f"Hello, {name}, yoau are {age} years old")

if __name__ == '__main__':
    app.run(debug=True, port=5000) 
```

Silakan update file `app.py` dengan script diatas, lalu akses `localhost:5000/query?name=Budi Setiawan`. Perhatikan error yang ditampilkan. Sekarang, cobalah akses  `localhost:5000/query?name=Budi Setiawan&age=32`. Lalu bandingkan ketika kita mengakses  `localhost:5000/query?age=32`. Dari contoh diatas, terdapat dua cara untuk mendaptkan arguments dari url yang dikirim oleh user. Pertama adalah dengan menggunakan `request.args[key]`. Namun cara ini cukup beresiko mengingat jika key tidak tersedia dalam url, maka akan terjadi server error. Cara pertama ini jarang digunakna kecuali jika kita memang mewajibkan adanya argumen tertentu. Cara yang kedua adalah `request.args.get(key)`. Cara kedua ini lebih sering digunakan karena secara otomatis akan memberikan nilai None jika key tidak terdapat dalam url.

Dalam API, penggunaan query arguments dapat sangat membantu terutama dalam endpoint dinamis. Kita akan pelajari bagaimana query arguments akan sangat membantu ktia dalam menyederhanakan pembuatan API server kita.

## API Methods

Senada dengan konsep **CRUD** (**C**reate, **R**read, **U**pdate, **D**elete) dalam database, dalam API konsep tersebut diadopsi menjadi 
- POST(CREATE), 
- GET(READ), 
- PUT(UPDATE), 
- DELETE

Secara konsep, method POST, GET, PUT, dan DELETE dibuat untuk mengatur API agar dapat lebih terstruktur. Meskipun pada prakterknya, endpoint yang kita definisikan menggunakan method "POST" tidaklah harus untuk membuat data. Artinya, tidak ada aturan yang mengharuskan kita untuk menuliskan jenis method dalam setiap endpoints kita (default endpoints menggunakan method GET). Namun, untuk tujuan kerapihan dan mengikuti kaidah yang benar, kita akan coba mendefinisikan endpoints kita dengan method tertentu, dan melihat manfaat dari penggunaan jenis method dalam setiap endpoint.

Berikut adalah contoh sederhana mengenai method POST dan GET
```python 
from flask import Flask, request 
app = Flask(__name__)

@app.route('/coba', methods=['GET', 'POST'])
def terserah():
    if request.method == 'GET':
        return "Ini adalah Hasil method GET"
    else:
        return "Ini adalah hasil method POST"


if __name__ == '__main__':
    app.run(debug=True, port=5000) 
```

Dan berikut adalah contoh yang lebih rumit
```python
from flask import Flask, request 
app = Flask(__name__)

@app.route('/form', methods=['GET', 'POST']) #allow both GET and POST requests
def form():
    if request.method == 'POST':  # Hanya akan tampil setelah melakukan POST (submit) form
        key1 = 'name'
        key2 = 'age'
        name = request.form.get(key1)
        age = request.form[key2]
        
        return (f'''<h1>Your Name  is: {name}</h1>
                   <h1>Your Age is: {age}</h1>
                ''')
   
    
    return '''<form method="POST">
                  Name: <input type="text" name="name"><br>
                  Age: <input type="text" name="age"><br>
                  <input type="submit" value="Submit"><br>
              </form>'''

if __name__ == '__main__':
    app.run(debug=True, port=5000) 
```

Silakan update file `app.py` kalian dengan sintaks diatas, lalu akses `localhost:5000/form`, aka akan muncul form sederhana dengan tombol "submit". Mengapa form tampil terlebih dahulu? karena dalam url `localhost:5000/form`, kita tidak mendefinisikan method kita sebagai POST atau GET. Maka, secara default request kita akan dianggap sebagai GET. Apakah kita bisa menentukan method kita dalam url? Kami sarankan untuk tidak mencobanya. 

Dalam sintaks diatas, kita mendefinisikan rute atau endpoint `/form` sebagai GET atau POST. Hal ini berarti endpoint tersebut dapat menerima request GET atau POST. 

Setelah kita mengisi form dan menekan tombol "submit", maka kita akan melakukan request POST dengan mengirimkan data-data berupa nama dan umur kepada server kita. Oleh sebab itu, server kita akan menjalankan perintah yang berada dalam kondisi `if request.method == 'POST':`

Cobalah untuk mengganti `if request.method == 'POST':` menjadi `if request.method == 'GET':`, maka kalian akan melihat perbedannya. 

Jika kalian penasaran, cobalah ubah `@app.route('/form', methods=['GET', 'POST'])` menjadi `@app.route('/form', methods=['POST'])`

## JSON Data Type

JSON adalah standar tipe data dalam pengiriman data dengan protokol HTTP. Pada dasarnya, JSON (JavaScript Object Name) sangat mirip, atau bisa dibilang identik dengan tipe data `dictionary` dalam python. Dictionary terdiri dari pasangan `key`:`value`. Berikut adalah contoh bentuk dan akses data dictionary.

In [ ]:
books = {'author': 'Anthony',
         'num_of_page': 123,
         'year' : 2019
        }
print(f"Pengaran buku: {books['author']}, dengan halaman {books['num_of_page']}, diterbitkan pada {books['year']}")

Kita akan mencoba mengirimkan data JSON menggunakan method POST ke endpoint kita. Dikarenakan browser biasa tidak bisa menangani hal tersebut, kita bisa gunakan [postman](https://www.getpostman.com/) atau jupyter notebook untuk membantu.
Silakan update file `app.py` dengan script berikut:

```python
from flask import Flask, request 
app = Flask(__name__) 

@app.route('/json', methods=['POST']) 
def json_exmp():
    
    req = request.get_json(force=True) # melakukan parsing data json, menyimpannya sebagai dictionary
    
    name = req['name']
    age = req['age']
    address = req['address']
    
    return (f'''Hello {name}, your age is {age}, and your address in {address}
            ''')

if __name__ == '__main__':
    app.run(debug=True, port=5000) #run app in debug mode on port 5000
```

Setelah server tersebut diupdate, kita akan coba melakukan request menggunakan library requests pada python

In [13]:
import requests

url = 'http://localhost:5000/json'
data = {"name" : "Andi", 
        "age" : 10,
        "address" : "Jakarta"
       }
r = requests.post(url,json=data) # pastikan gunakan requests.pos, bukan requests.get
print(r)

<Response [200]>

Response 200 berarti API kita berhasil mengirimkan atau melakukan request yang kita kirim. Untuk mempelajari jenis-jenis repsonse yang dikirimkan melalui HTTP, silakan merujuk ke [sumber ini](https://restfulapi.net/http-status-codes/). Objek yang kita kirimkan berupa `requests.models.Response`. Untuk mendapatkan isi dari respon tersebut, kita dapat gunakan `.text` atau `.content`

In [24]:
print(type(r))

<class 'requests.models.Response'>

In [28]:
print(r.content)
print(r.text)

b'Hello Andi, your age is 10, and your address in Jakarta\n            '
Hello Andi, your age is 10, and your address in Jakarta

## Data Fetching

Kembali ke tujuan utama, kita akan mencoba membuat API yang mampu mengirimkan data dalam bentuk DataFrame (dalam format JSON). Dalam hal ini, kita akan coba menggunakan data `books_c.csv` yang terdapat dalam folder `data_input`. Dalam contoh kali ini, kita akan mengaplikasikan dynamic routing. Konsepnya adalah kita tidak secara eksplisit membuat route atau endpoint, melainkan menyimpannya dalam variabel. Hal ini akan sangat berguna jika data yang ingin kita berikan sangat beragam dan bergantung pada keinginan user.

Untuk melakukan dynamic routing, cukup simpan variabel kedalam tanda `< >`, lalu masukkan variabel tersebut sebagai parameter fungsi di endpoint yang bersangkutan.

```python 
from flask import Flask, request 
import pandas as pd 
app = Flask(__name__) 

# mendapatkan keseluruhan data dari <data_name>
@app.route('/data/get/<data_name>', methods=['GET']) 
def get_data(data_name): 
    data = pd.read_csv('data/' + str(data_name))
    return (data.to_json())
    

# mendapatkan data dengan filter nilai <value> pada kolom <column>
@app.route('/data/get/equal/<data_name>/<column>/<value>', methods=['GET']) 
def get_data_equal(data_name, column, value): 
    data = pd.read_csv('data/' + str(data_name))
    mask = data[column] == value
    data = data[mask]
    return (data.to_json())

if __name__ == '__main__':
    app.run(debug=True, port=5000) 
```

Untuk meminta data menggunakan API yang telah ada, silakan jalankan cells berikut

In [104]:
import requests
import pandas as pd

In [105]:
url1 = 'http://127.0.0.1:5000/describe_book'
r = requests.get(url1)
r_pd = pd.DataFrame(r.json())

In [106]:
r_pd.head()

,bookID,average_rating,isbn13,# num_pages,ratings_count,text_reviews_count
count,13714.000000,13714.000000,1.371400e+04,13714.000000,13714.000000,13714.000000
mean,22159.859195,3.930620,9.764017e+12,342.402727,17765.397258,533.632128
std,13700.926816,0.357893,3.987679e+11,252.650165,112957.225577,2529.006691
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000,0.000000
25%,10619.250000,3.770000,9.780345e+12,196.000000,83.000000,7.000000

In [62]:
url2 = 'http://localhost:5000/data/get/equal/books_c.csv/isbn/0439785960'
r = requests.get(url2)
r_pd = pd.DataFrame(r.json())
r_pd.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.56,0439785960,9780439785969,eng,652,1944099,26249

In [64]:
url3 = 'http://localhost:5000/data/get/equal/books_c.csv/authors/J.K. Rowling'
r = requests.get(url3)
r_pd = pd.DataFrame(r.json())
r_pd.tail()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
12257,41912,Harry Potter ve Felsefe Taşı,J.K. Rowling,4.47,3570211010,9783570211014,tur,353,12,0
12660,43504,Harry Potter and the Philosopher's Stone (Harr...,J.K. Rowling,4.47,158234681X,9781582346816,gla,250,11,0
12663,43509,Harry Potter and the Goblet of Fire (Harry Pot...,J.K. Rowling,4.55,074754624X,9780747546245,eng,636,18097,860
13634,47523,Harry Potter Boxed Set (Harry Potter #1-4),J.K. Rowling,4.67,0439434866,9780439434867,eng,1820,534,6
13637,47532,Harry Potter y el prisionero de Azkaban (Harry...,J.K. Rowling,4.55,8478886559,9788478886555,spa,359,5582,469

Dari contoh diatas, kita sudah dapat melakukan fetching data menggunakan API dan seberapa bermanfaatnya melakukan dynamic routing. Kedepannya, diharapkan pengetahuan ini dapat dikembangkan dengan melakukan fetching data dari database.

## Deploying Flask APP

Sekarang, setelah Flask App kita sudah berhasil dijalankan, kita akan coba deploy app tersebut **(beserta environmentnya)** ke app hosting/web hosting/cloud. Untuk saat ini, kita akan menggunakan [heroku](https://www.heroku.com/) karena **gratis**. Untuk melakukan deployment, silakan registrasi akun baru. 

Langkah ini dapat kalian ikuti pada [sumber ini](https://stackabuse.com/deploying-a-flask-application-to-heroku/)

### Get the requirements

Silakan buat environment baru, lalu hanya install `pandas`, `flask`, dan `gunicorn`. Setelah libary tersebut berhasil diinstal, jalankan `pip freeze > requirements.txt` untuk mengeksport semua library kedalam file `requirements.txt`. Perlu diingat bahwa Heroku hanya bisa mengenali libary yang kita pakai jika kita menuliskannya kedalam requirements.txt

### Create Heroku App
Untuk membuat heroku app, cukup klik new->app pada dashboard heroku. Perlu diingat bahwa nama app di heroku haruslah unik.

### Deployment

Setelah kita membuat dan menamai app kita di heroku, kita harus mengupload file app kita dari lokal. Untuk melakukan hal ini, kita akan menggunakan git. Cara termudah adalah dengan membuat repository baru di github, lalu sambungkan aplikasi heroku degan repository github tersebut. 
![](res/deploy-1.PNG)

Nyalakan `Automatic Deploy` jika ingin melakukan deployment ulang setiap terjadi perubahan pada repositoy secara otomatis (kurang disarankan). Setelah repository terhubung, klik tombol deploy branch yang berada di bagian bawah app heroku (jika tidak ada branch pada repository github, secara default branch master yang akan dipilih). 

![](res/deploy-2.PNG)

# Test Your API Endpoints

Setelah deployment app kita behasil, kita bisa mencoba mengaksesnya melalui browser, atau jupyter notebook(lebih disarankan). Mari coba beberapa endpoints yang telah kita coba lakukan di lokal. 

Untuk catatan, tidak perlu menuliskan port pada url heroku, karena kita sudah mengaturnya pada file `Procfile`

In [4]:
import requests
import pandas as pd 
heroku_url = 'https://algo-capstone.herokuapp.com/data/get/books_c.csv'
r = requests.get(heroku_url)
r_pd = pd.DataFrame(r.json())
r_pd

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.56,0439785960,9780439785969,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.49,0439358078,9780439358071,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,0439554934,9780439554930,eng,320,5629932,70390
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,0439554896,9780439554893,eng,352,6267,272
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.55,043965548X,9780439655484,eng,435,2149872,33964
...,...,...,...,...,...,...,...,...,...,...
13709,47699,M Is for Magic,Neil Gaiman-Teddy Kristiansen,3.82,0061186422,9780061186424,eng,260,11317,1060
13710,47700,Black Orchid,Neil Gaiman-Dave McKean,3.72,0930289552,9780930289553,eng,160,8710,361
13711,47701,InterWorld (InterWorld #1),Neil Gaiman-Michael Reaves,3.53,0061238961,9780061238963,en-US,239,14334,1485
13712,47708,The Faeries' Oracle,Brian Froud-Jessica Macbeth,4.43,0743201116,9780743201117,eng,224,1550,38
13713,47709,The World of The Dark Crystal,Brian Froud,4.29,1862056242,9781862056244,eng,132,3572,33

# Document your API

Hal terpenting dalam pembuatan API adalah dokumentasi. Aplikasi yang bagus harus memiliki dokumentasi untuk user yang belum tahu cara menggunakannya. Hal ini juga memudahkan tim kami untuk melakukan penilaian. Oleh karena itu, buatlah dokumentasi API sederhana dengan format : 
- Deskripsi API 
- Endpoints
___
```
Deskripsi: (Contoh Dokumentasi)
API ini dinominasikan sebagai capstone project yang berguna untuk mengirimkan data kepada user. Proses wrangling dilakukan sesuai endpoint-endpoint yang dimaksud. Base url dari aplikasi ini adalah https://algo-capstone.herokuapp.com

Endpoints: 
    1. / , method = GET
    Merupakan endpoint home, dan akan mengembalikan nilai berupa string selamat datang
    
    2. /data/get/<data_name> , method = GET
    Mengembalikan data <data_name> dalam bentuk JSON. Beberapa data yang tersedia adalah : 
        - books_c.csv
        - pulsar_stars.csv (tidak digunakan, hanya contoh saja)
        
    3. /data/get/equal/<data_name>/<column>/<value>
    Mengembalikan <data_name> yang telah di filter dimana nilai pada <column> = <value>

```
___

# Tips

Jika dirasa ada kesulitan untuk menentukan informasi apa yang akan dikirimkan dalam sebuah endpoint (membuat endpoint), cobalah beralih ke sudut pandang user. Sebagai user, informasi apa yang ingin kita dapatkan dari data tersebut? Akan ada sangat banyak kemungkinan yang bisa diambil. Kalian bisa melakukannya! 

Happy Coding !
~ Team Algoritma